import os
from dotenv import load_dotenv

load_dotenv()

API_KEY_COINGLASS = os.getenv("COINGLASS_API_KEY")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

THRESHOLD_LIQUIDATION_USD = 10000000
PRICE_DROP_PCT = 2.5
REBOUND_PCT = 0.75
TIME_WINDOW_SECONDS = 900
